### ISSUE TITLE
Decorating generator functions, impossible?

### ISSUE THREAD

**Issue by silkentrance** [loganfsmyth/babel-plugin-transform-decorators-legacy#26]
Just stumbled across this one

```
function decorator(target, attr, descriptor)
{
    return descriptor;
}


class Foo
{
    @decorator
    * gen() { yield 1; }
}
```

will result in the following error

```
SyntaxError: src/test.es: Unexpected token (xx:xx)
  xx |     @decorator
> xx |     *gen() { yield 1; }
```

Is this by design or can this be fixed?

Because, when doing this instead

```
class Foo
{
    @decorator
    async gen() {}
}
```

the decorator will be applied just fine.

And, by looking at the spec, in 14.3 it states that the GeneratorDefinition from 14.4 is a valid MethodDefinition.

And according to https://github.com/wycats/javascript-decorators#grammar PropertyDefinition refers to MethodDefinition.

**Comment by loganfsmyth** [comment]
This plugin doesn't have much in the way of control over this since it relies on Babylon. Feel free to file this on https://github.com/babel/babylon though, it's probably worth raising again. This was originally on purpose which can be seen in https://phabricator.babeljs.io/T2014 and then the spec was updated but it essentially got rolled into https://phabricator.babeljs.io/T2645. The overall updated spec has taken much longer than we originally expected, so maybe it's worth revisiting tweaking the parser for now to allow it.

**Comment by silkentrance** [comment]
@loganfsmyth thanks you very much for the pointers.

Just as a reminder for myself: bug in babylon https://github.com/babel/babylon/blob/master/src/parser/expression.js#L709
