### ISSUE TITLE
Decorators not applied on non-inline functions in object literals

### ISSUE THREAD

**Issue by nrabinowitz** [loganfsmyth/babel-plugin-transform-decorators-legacy#34]
The current transformation treats functions in object literals differently depending on whether they are inlined or referenced. I am trying to apply a simple wrapper decorator to functions in an object literal, as in this example:

``` javascript
function decorator(target, name, descriptor) {
  const original = descriptor.value;
  descriptor.value = function decorated() {
    console.log(`wrapper: ${name}`);
    return original(...arguments);
  };
}

function foo() {
  console.log('foo');
}

const obj = {
  // Referenced function is not decorated
  @decorator foo,
  // Inline function is decorated
  @decorator bar() {
    console.log('bar');
  }
};
```

I would expect these syntaxes to work identically, but they do not:

``` javascript
obj.foo();
// "foo"
obj.bar();
// "wrapper: bar"
// "bar"
```

I found a workaround, but it's fairly ugly, because it needs to refer to the `initializer` property of the descriptor, which seems to be internal to this plugin:

``` javascript
function decorator(target, name, descriptor) {
  const original = descriptor.initializer ?
    descriptor.initializer() :
    descriptor.value;
  delete descriptor.initializer;
  descriptor.value = function decorated() {
    console.log(`wrapper: ${name}`);
    return original(...arguments);
  };
}
```

**Comment by loganfsmyth** [comment]
This was the existing behavior from Babel 5. Just like the proposed class-properties syntax, object properties are also considered "initializer" values. e.g.

```
class Foo {
  prop = 4;
}

var obj = {
  prop2: 4,
}
```

are conceptually similar where a value is being defined on the target object, whereas `{method(){}}` is declaring a method as part of the object, rather than a value defined on it, so one is treated as an initializer and one is treated as a value. `initializer` is not something that the Babel plugin invented, they are from the Decorators spec: https://github.com/wycats/javascript-decorators/blob/master/interop/initializer.md

I don't disagree that this is likely confusing, but it's not my place to change any of this behavior. Until there is a formal specification that we can reference that says what the behavior should be, other than the existing spec + Babel 5's behavior, this is unlikely to change.

Keep in mind, decorators are entirely experimental at this point with good reason :)

Your "ugly" approach seems fine to me. I will add through that `return original(...arguments);` would be better as `return original.apply(this, arguments);` since in the general decorator case, you have no idea whether the call context is important for a function or not.
