### ISSUE TITLE
Why legacy?

### ISSUE THREAD

**Issue by sergeysova** [loganfsmyth/babel-plugin-transform-decorators-legacy#4]
Why decorators was removed from Babel?
I use it in many projects.

``` js
function Hack(classTarget) {
  classTarget.prototype.method = function() {
    console.log("Echo:", this.echo);
  }
}


@Hack
class Random {
  constructor() {
    this.echo = "Entropy";
  }
}


let obj = new Random();
obj.method();
```

**Comment by themouette** [comment]
You can find more information on this [babel issue](http://phabricator.babeljs.io/T2645#65806)

**Comment by loganfsmyth** [comment]
Leaving this open as a TODO for myself to add to the README. As @themouette said, that issue is a good source of info. Here's my post from there: http://phabricator.babeljs.io/T2645#67560

This module should allow you to use decorators like you did in Babel 5. Some things are still lacking, but simpler decorators to mutate values should work.

**Comment by loganfsmyth** [comment]
I added a bit more of a note to the README.
