### ISSUE TITLE
Update readme to reflect recent changes?

### ISSUE THREAD

**Issue by callumlocke** [loganfsmyth/babel-plugin-transform-decorators-legacy#45]
TC39 now says [decorators are stage 2](https://github.com/tc39/proposals). Could this plugin's readme be updated to reflect the current status?

My impression (after an hour of reading conflicting info in various readmes) is that decorators are now well and truly on the standards track, and we're now waiting for an official Babel plugin. But I'm not clear on whether the official plugin will be essentially the same as this 'legacy' one, or if they will work differently. In other words I want  some guidance on whether I should start using decorators today via this plugin - will it be easy to switch?

If you know the current situation it would be great to explain it the 'why legacy' section in this readme.

**Comment by hybrist** [comment]
There are pretty big changes between the stage 1 proposal (which this transform implements) and the stage 2 proposal. No decorator written against this transform will work with what is currently on the standards track (afaict at least). So it seems to make sense to keep this as "-legacy" because people who depend on the old decorator interface might still need it, even if babel starts including an updated transform.

**Comment by loganfsmyth** [comment]
We're planning to deprecate this and move it back to `babel-plugin-transform-decorators` soon, and then iterate on it there for updates to the new spec. Still working out how we want to do versioning, but not worth tracking this in this repo.
